# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - payroll

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://payrollv2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b4bce81048654377ae519656d8088bba }}
        password: ${{ secrets.AzureAppService_ContainerPassword_50ef88a292a44a41a949e799ce60e862 }}

    - name: Set lowercase registry user
      id: vars
      run: |
        echo "username_lc=$(echo '${{ secrets.AzureAppService_ContainerUsername_b4bce81048654377ae519656d8088bba }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: payrollv2.azurecr.io/${{ steps.vars.outputs.username_lc }}/payroll:${{ github.sha }}
        file: ./Dockerfile
