# File: .github/workflows/azure-webapp-container.yml

name: Build and deploy container app to Azure Web App - payroll

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: payrollv2.azurecr.io
  IMAGE_NAME: payroll

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.AzureAppService_ContainerUsername_b4bce81048654377ae519656d8088bba }}
        password: ${{ secrets.AzureAppService_ContainerPassword_50ef88a292a44a41a949e799ce60e862 }}

    - name: Convert ACR username to lowercase
      id: acr-user
      run: |
        echo "username_lc=$(echo '${{ secrets.AzureAppService_ContainerUsername_b4bce81048654377ae519656d8088bba }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Build and push Docker image to ACR
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ steps.acr-user.outputs.username_lc }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production

    steps:
    - name: Deploy container to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'payroll' # This is the App Service name in Azure
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_19cb285f90754695b4f01b809e17cfc8 }}
        images: ${{ env.REGISTRY }}/${{ steps.acr-user.outputs.username_lc }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
