name: Build and deploy container app to Azure Web App - payroll

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          REPOSITORY_NAME=$(echo "YOUR_REPOSITORY_NAME" | tr '[:upper:]' '[:lower:]')
          docker buildx build --file ./Dockerfile --iidfile /tmp/docker-build-push-qHIUQC/iidfile --secret id=GIT_AUTH_TOKEN,src=/tmp/docker-build-push-qHIUQC/tmp-2533-4itZaM3VjRPc --tag $REPOSITORY_NAME/payroll:180f1df4f2ddaad84d8b87e1b47354030fead326 --metadata-file /tmp/metadata.json .
