name: Build and deploy container app to Azure Web App - payroll

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_REGISTRY_USERNAME }}/payroll:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'payroll'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_35bc2e550ad04dd79274856f4f4aa4cd }}
        images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_REGISTRY_USERNAME }}/payroll:${{ github.sha }}
